services:
  spring-festival-adventure:
    image: spring-festival-adventure:latest
    container_name: spring-festival-adventure
    restart: unless-stopped

    ports:
      - "3002:3002"

    env_file:
      - path: .env
        required: false

    volumes:
      - counter-data:/app/data

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  counter-data: